spring.application.name=grievance-management-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/grievancesystem_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ayu5hika}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:dataupload2005@gmail.com}
spring.mail.password=${MAIL_PASSWORD:veds veco leuw dwrr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8082}